name: dog
description: Simple and pretty log package for Dart, includes Flutter and web.
version: 1.3.2
repository: https://github.com/chenenyu/dog
publish_to: https://pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  stack_trace: ^1.10.0
  tuple: ^2.0.0

dev_dependencies:
  http: ^0.13.0
  path: ^1.8.0
  lints: ^1.0.0
