name: dog
description: Simple and pretty log package for Dart, includes Flutter and web.
version: 1.1.0
repository: https://github.com/chenenyu/dog
publish_to: https://pub.dev

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  ansicolor: ^1.0.5
  stack_trace: ^1.9.5
