name: dog
description: Simple and pretty log package for Dart.
version: 0.4.0
repository: https://github.com/chenenyu/dog
publish_to: https://pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ansicolor: ^1.0.5
  stack_trace: ^1.9.5
